### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by kuceram** [amio-io/amio-chatbot-builder-js#10]
Navrhy
- amio-bot-builder
- amio-bot
- amio-bot-framework
- amio-chatbot

Ja jsem pro to prvni. `*-js` asi pouzijeme kvuli Githubu, na npm bych ale sel bez toho... Co vy na to @karelrochelt @zatziky

**Comment by zatziky** [comment]
Měli jsme o tom slovní diskuzi v červenci. Ty tvé názvy tam padali. Dohodli jsme se na tom nynějším názvu. Nebudu se bránit přejmenování, ale jestli není pádný argument, tak bych na to kašlal.
![image](https://user-images.githubusercontent.com/2794365/46201113-b13a8f00-c313-11e8-90e3-a98a619e2537.png)

**Comment by kuceram** [comment]
zacalo me vadit ted spis to `*-js`, kdyz jsi v npm tak to vis ze jsi v JavaScript. Ale zatim kaslem na to :-)

**Comment by zatziky** [comment]
to můžeme odstanit v `package.json`.
